[providers]
elixir = "1.16.3"
erlang = "26.2.5"

[variables]
MIX_ENV = "prod"

[build]
cmds = [
    "mix deps.get --only prod",
    "mix deps.compile", 
    "mix assets.deploy",
    "mix phx.digest",
    "mix release"
]

[start]
cmd = "./railway-start.sh"