[phases.setup]
nixPkgs = ['elixir', 'nodejs', 'erlang']

[phases.build]
cmds = [
  'mix local.hex --force',
  'mix local.rebar --force',
  'mix deps.get --only prod',
  'mix compile',
  'mix assets.deploy',
  'mix release jesus_sayings_search_umbrella'
]

[start]
cmd = "_build/prod/rel/jesus_sayings_search_umbrella/bin/jesus_sayings_search_umbrella start"